AppSetting.create(name:"'system/uploads/endpoint'")
AppSetting.create(name:"'client_build_version'")
AppSetting.create(name:"'client_build_version'")
AppSetting.create(name: "'expiry_time_rules'")
AppSetting.create(name:"'system/language_default'")
AppSetting.create(name: "'localization_path'")
AppSetting.create(name:"'system/language_translation'")
AppSetting.create(name:"'system/language_manage'")
AppSetting.create(name: "'basic_expiries'")
AppSetting.create(name: "'move_effect_array'")
AppSetting.create(name:"'is_cloud_environment'")
AppSetting.create(name: "'warn_on_move_if_expiry_less_than'")
AppSetting.create(name: "'warn_on_prepare_if_expiry_less_than'")
AppSetting.create(name: "'warn_if_not_fed_for_more_than'")
AppSetting.create(name: "'warn_for_frozen_expiring_bottles'")
AppSetting.create(name: "'warn_for_unfrozen_expiring_bottles'")
AppSetting.create(name: "'white_list_ips'")
AppSetting.create(name: "'hospital/default_status_for_adding_hospital'")
AppSetting.create(name: "'milkbank/default_status_for_adding_milk_bank'")
AppSetting.create(name: "'allow_unstored_milk'")
AppSetting.create(name: "'has_fridge'")
AppSetting.create(name: "'has_deep_freezers'")
AppSetting.create(name: "'unstored_warm_water_bath'")
AppSetting.create(name: "'unstored_cold_water_bath'")
AppSetting.create(name: "'fridge_water_bath'")
AppSetting.create(name: "'unapproved_freezer'")
AppSetting.create(name: "'research_freezer'")
AppSetting.create(name: "'storage/milk_storage_types'")
AppSetting.create(name: "'report_printer'")
AppSetting.create(name: "'auto_generate_outpatient_barcode'")
AppSetting.create(name: "'auto_generate_delivery_barcode'")
AppSetting.create(name: "'show_outpatient_id_as_mrn'")
AppSetting.create(name: "'auto_generate_user_barcode'")
AppSetting.create(name: "'optional_auto_generate_donor_barcode'")
AppSetting.create(name: "'auto_generate_milkbank_barcode'")
AppSetting.create(name: "'auto_generate_location_barcode'")
AppSetting.create(name: "'optional_auto_generate_milkbank_barcode'")
AppSetting.create(name: "'auto_generate_hospital_barcode'")
AppSetting.create(name: "'optional_auto_generate_hospital_barcode'")
AppSetting.create(name: "'auto_generate_researchfacility_barcode'")
AppSetting.create(name: "'optional_auto_generate_researchfacility_barcode'")
AppSetting.create(name: "'outpatient/show_parent_name'")
AppSetting.create(name: "'barcode_base_number'")
AppSetting.create(name: "'barcode_user_prefix'")
AppSetting.create(name: "'barcode_donor_prefix'")
AppSetting.create(name: "'barcode_outpatient_prefix'")
AppSetting.create(name: "'barcode_hospital_prefix'")
AppSetting.create(name: "'barcode_milkbank_prefix'")
AppSetting.create(name: "'barcode_research_facility_prefix'")
AppSetting.create(name: "'barcode_doctor_prefix'")
AppSetting.create(name: "'barcode_deposit_prefix'")
AppSetting.create(name: "'barcode_bottle_prefix'")
AppSetting.create(name: "'barcode_pool_prefix'")
AppSetting.create(name: "'barcode_pool_bottle_prefix'")
AppSetting.create(name: "'barcode_milk_batch_prefix'")
AppSetting.create(name: "'barcode_deposit_group_prefix'")
AppSetting.create(name: "'print_labels_in_reverse'")
AppSetting.create(name: "'print_aztec_labels'")
AppSetting.create(name:	"'printer/set_label_darkness'")
AppSetting.create(name:	"'printers/default_density'")
AppSetting.create(name: "'printers/default_dpi'")
AppSetting.create(name: "'printers/dpi_possible_values'")
AppSetting.create(name: "'printers/edit/allow_change_dpi'")
AppSetting.create(name: "'printers/edit/allow_change_density'")
AppSetting.create(name: "'printers/density_possible_values'")
AppSetting.create(name: "'print_logo_labels'")
AppSetting.create(name: "'logo_label_dropdown_options'")
AppSetting.create(name: "'password_reset_link_expiry'")
AppSetting.create(name:"'use_fridge_as_freezer'")
AppSetting.create(name:"'store_hashed_password_in_error_log'")
AppSetting.create(name:"'password/cant_contain_account_name_parts'")
AppSetting.create(name: "'password_length'")
AppSetting.create(name: "'password_days'")
AppSetting.create(name: "'password_hash_cost'")
AppSetting.create(name:"'password/number_of_uniques_before_same'")
AppSetting.create(name:"'password/number_to_keep'")
AppSetting.create(name:"'password/requires_uppercase_character'")
AppSetting.create(name:"'password/requires_lowercase_character'")
AppSetting.create(name:"'password/requires_number'")
AppSetting.create(name:"'password/requires_special_character'")
AppSetting.create(name:"'password/minimum_character_rule_requirements'")
AppSetting.create(name:"'password/number_to_keep'")
AppSetting.create(name: "'seconds_before_timeout'")
AppSetting.create(name: "'absolute_timeout'")
AppSetting.create(name: "'milk_count_dropdown_options'")
AppSetting.create(name: "'deposit_count_dropdown_options'")
AppSetting.create(name: "'default_number_of_bottles'")
AppSetting.create(name: "'require_issue_labels'")
AppSetting.create(name: "'require_receive_labels'")
AppSetting.create(name: "'track_expiry'")
AppSetting.create(name: "'track_location'")
AppSetting.create(name: "'storage/store_in_locations'")
AppSetting.create(name:"'locations/use_barcode'")
AppSetting.create(name:"'locations/barcode_prefix'")
AppSetting.create(name:"'printer/set_default'")
AppSetting.create(name: "'files_to_print_location'")
AppSetting.create(name: "'files_printed_location'")
AppSetting.create(name: "'allow_prepare'")
AppSetting.create(name: "'allow_combine'")
AppSetting.create(name: "'allow_split'")
AppSetting.create(name: "'audio/feedback_on_error'")
AppSetting.create(name: "'db_username'")
AppSetting.create(name: "'db_password'")
AppSetting.create(name: "'db_host'")
AppSetting.create(name: "'db_dbname'")
AppSetting.create(name: "'db_username'")
AppSetting.create(name: "'db_password'")
AppSetting.create(name: "'db_dbname'")
AppSetting.create(name: "'db_dbname_bmt'")
AppSetting.create(name:"'db_data_version'")
AppSetting.create(name: "'db_hour_offset'")
AppSetting.create(name: "'archive/dbdump_path'")
AppSetting.create(name: "'archive/path/temp'")
AppSetting.create(name: "'archive/path/data'")
AppSetting.create(name: "'archive/backup_dates/daily'")
AppSetting.create(name: "'archive/backup_dates/weekly'")
AppSetting.create(name: "'archive/backup_dates/monthly'")
AppSetting.create(name: "'archive/backup_dates/yearly'")
AppSetting.create(name: "'archive/labels_printed_age'")
AppSetting.create(name: "'archive/hl7_messages_age'")
AppSetting.create(name: "'archive/archive_path'")
AppSetting.create(name: "'cal_per_oz_label'")
AppSetting.create(name: "'css/div.success-text/background'")
AppSetting.create(name: "'system/force_https'")
AppSetting.create(name: "'system/force_https/ignore_hosts'")
AppSetting.create(name: "'system/disable_activex'")
AppSetting.create(name: "'system/use_user_groups'")
AppSetting.create(name: "'system/allow_website_messages'")
AppSetting.create(name: "'system/use_tour_functionality'")
AppSetting.create(name: "'system/use_direct_thermal_printers'")
AppSetting.create(name: "'system/block_ctrl_keys'")
AppSetting.create(name: "'system/use_db_city_and_region'")
AppSetting.create(name: "'system/barcode_version'")
AppSetting.create(name: "'system/allow_small_resolution'")
AppSetting.create(name: "'system/recall/contact_information'")
AppSetting.create(name:"'system/volume/ml_to_oz_conversion_factor'")
AppSetting.create(name:"'system/csv/pregenerate_donor_csv'")
AppSetting.create(name:"'system/csv/pregenerate_outpatient_csv'")
AppSetting.create(name:"'system/folder_scan/files_to_ignore'")
AppSetting.create(name:"'system/login/request_account'")
AppSetting.create(name:"'system/login/sent_account_request_to'")
AppSetting.create(name:"'batch/set_expiration_time_from_time_of_pasteurization'")
AppSetting.create(name:"'batch/set_expiration_custom_error_text'")
AppSetting.create(name:"'batch/default_pasteurizer_id'")
AppSetting.create(name:"'batch/set_expiration_time_based_on_minimum_expiration_time'")
AppSetting.create(name:"'dashboard/show_bottles'")
AppSetting.create(name:"'dashboard/rows_per_section'")
AppSetting.create(name:"'dashboard/mark_milk_expiring_within_n_days'")
AppSetting.create(name:"'dashboard/available_pools/show_milk_types'")
AppSetting.create(name:"'dashboard/available_batches/show_milk_types'")
AppSetting.create(name: "'ldap_login/enable'")
AppSetting.create(name: "'ldap_login/server_name'")
AppSetting.create(name: "'ldap_login/server_port'")
AppSetting.create(name: "'ldap_login/login_prefix'")
AppSetting.create(name: "'ldap_login/use_remote_login_username'")
AppSetting.create(name: "'ldap_login/domain'")
AppSetting.create(name:"'login/login_with_user_email'")
AppSetting.create(name: "'printers/ftp/timeout'")
AppSetting.create(name: "'scanners/pc/append_enter'")
AppSetting.create(name: "'system/pc/block_blur_after_append_enter'")
AppSetting.create(name: "'bottle_count_dropdown_options'")
AppSetting.create(name:"'custom_time_format'")
AppSetting.create(name: "'label_expiry_date_format'")
AppSetting.create(name: "'label_expiry_date_format'")
AppSetting.create(name:"'use_modified_canadian_short_date_format'")
AppSetting.create(name: "'year_dropdown_start'")
AppSetting.create(name: "'year_dropdown_end'")
AppSetting.create(name: "'lockout_after_incorrect_logins'")
AppSetting.create(name: "'enforce_single_session_for_user'")
AppSetting.create(name: "'minimum_error_to_record'")
AppSetting.create(name: "'show_debug_information'")
AppSetting.create(name: "'outpatient/popup_required'")
AppSetting.create(name:"'outpatient/select_doctors_from_dropdown'")
AppSetting.create(name: "'milk_finder_report_milk_types_stlukes'")
AppSetting.create(name: "'available_dispensation_report_milk_types'")
AppSetting.create(name: "'show_report_totals_on_bottom'")
AppSetting.create(name: "'allow_pcs'")
AppSetting.create(name: "'allow_prepare_during_feed'")
AppSetting.create(name: "'basic_donor_expiries'")
AppSetting.create(name: "'prepare/split/default_number_of_bottles'")
AppSetting.create(name: "'warn_for_frozen_expiring_bottles'")
AppSetting.create(name: "'warn_for_unfrozen_expiring_bottles'")
AppSetting.create(name: "'ldap_login/server_name'")
AppSetting.create(name: "'ldap_login/server_port'")
AppSetting.create(name: "'ldap_login/login_prefix'")
AppSetting.create(name: "'ldap_login/use_remote_login_username'")
AppSetting.create(name: "'print_bottles/bottle_count_dropdown_options'")
AppSetting.create(name: "'allow_return_bottles_to_mother'")
AppSetting.create(name: "'use_orm'")
AppSetting.create(name:"'enable_outpatient_regex_filter'")
AppSetting.create(name: "'enable_hospital_regex_filter'")
AppSetting.create(name:"'enable_milk_regex_filter'")
AppSetting.create(name: "'enable_mother_regex_filter'")
AppSetting.create(name: "'enable_bin_regex_filter'")
AppSetting.create(name: "'enable_location_regex_filter'")
AppSetting.create(name: "'regex_filter_outpatient_input'")
AppSetting.create(name: "'regex_filter_hospital_input'")
AppSetting.create(name: "'regex_filter_baby_input'")
AppSetting.create(name: "'regex_filter_milk_input'")
AppSetting.create(name: "'regex_filter_mother_input'")
AppSetting.create(name: "'regex_filter_bin_input'")
AppSetting.create(name: "'regex_filter_location_input'")
AppSetting.create(name: "'regex_replace_baby_input'")
AppSetting.create(name: "'regex_replace_outpatient_input'")
AppSetting.create(name: "'regex_replace_hospital_input'")
AppSetting.create(name: "'regex_replace_milk_input'")
AppSetting.create(name: "'regex_replace_mother_input'")
AppSetting.create(name: "'regex_replace_location_input'")
AppSetting.create(name: "'regex_replace_bin_input'")
AppSetting.create(name: "'regex_milk_type_name_input'")
AppSetting.create(name: "'system/milkbank_name'")
AppSetting.create(name: "'system/milkbank_shortname'")
AppSetting.create(name:"'ui/text/date_blood_results_received'")
AppSetting.create(name: "'system/milkbank_number'")
AppSetting.create(name: "'system/customer_service_number'")
AppSetting.create(name: "'system/donor_barcode_max_length'")
AppSetting.create(name: "'system/milkbank_barcode_max_length'")
AppSetting.create(name: "'system/location_barcode_max_length'")
AppSetting.create(name: "'system/unit_of_measurement'")
AppSetting.create(name:"'auto_blur_bottle_length'")
AppSetting.create(name:"'system/cloud_printing/use_qz_tray'")
AppSetting.create(name:"'system/cloud_printing/qz/regex_to_filter_printer_list'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'system/bottle_volumes'")
AppSetting.create(name:"'store/allow_refreeze'")
AppSetting.create(name:"'generate_batch_barcodes'")
AppSetting.create(name:"'system/allow_resetting_volume'")
AppSetting.create(name:"'system/global/use_auto_complete_for_locations'")
AppSetting.create(name:"'system/global/store_in_default_location'")
AppSetting.create(name:"'system/print/dispense_labels_to_donors'")
AppSetting.create(name:"'system/require_unique_bottle_scanning_for_packing'")
AppSetting.create(name:"'milkdepot_default_region'")
AppSetting.create(name:"'security/open_pop_window'")
AppSetting.create(name:"'security/disable_right_click'")
AppSetting.create(name:"'pool/print_volume_on_label'")
AppSetting.create(name:"'donor/use_expected_due_date_visual_only'")
AppSetting.create(name: "'auto_generate_donor_barcode'")
AppSetting.create(name:"'donor/track_donors_dob'")
AppSetting.create(name:"'donor/donor_email_required'")
AppSetting.create(name:"'donor/show_notes'")
AppSetting.create(name:"'donor/display_work_info'")
AppSetting.create(name:"'donor/display_work_info/source'")
AppSetting.create(name:"'donor/display_work_info/position'")
AppSetting.create(name:"'donor/collect_spouse_info'")
AppSetting.create(name:"'donor/collect_baby_last_name'")
AppSetting.create(name:"'donor/number_of_exclusions'")
AppSetting.create(name:"'donor/number_of_followups'")
AppSetting.create(name:"'donor/exclusion_track_time'")
AppSetting.create(name:"'donor/export_csv'")
AppSetting.create(name:"donor/require_dob")
AppSetting.create(name:"'donor/set_baby_status'")
AppSetting.create(name:"'donor/track_baby_gestational_info'")
AppSetting.create(name:"'donor/set_baby_status_default'")
AppSetting.create(name:"'postalcode_zipcode_ui_text'")
AppSetting.create(name:"'province_state_ui_text'")
AppSetting.create(name:"'donor/blood_results_received_ui_text'")
AppSetting.create(name:"'donor/track_repeat_donors'")
AppSetting.create(name:"'donor/use_blood_screening_number'")
AppSetting.create(name:"'donor/track_lab_approval_dates'")
AppSetting.create(name:"donor/upload_donor_results")
AppSetting.create(name:"donor/auto_update_donor_results_fields")
AppSetting.create(name:"donor/upload_donor_results_file")
AppSetting.create(name:"donor/upload_donor_results_file_version")
AppSetting.create(name:"'donor/obform_ui'")
AppSetting.create(name:"'donor/default_status_for_adding_user'")
AppSetting.create(name:"'print_multiple_donor_labels'")
AppSetting.create(name:"'donor/displayed_all_lab_approvals_name'")
AppSetting.create(name:"'donor/screening_reading_text'")
AppSetting.create(name:"'donor/screening_use_radio_instead_of_checkbox'")
AppSetting.create(name:"'donor/require_baby_dob'")
AppSetting.create(name:"'donor/track_baby_death_info'")
AppSetting.create(name:"'donor/track_baby_is_deceased'")
AppSetting.create(name:"'donor/search/display_donor_location'")
AppSetting.create(name:"'donor/search/display_baby_first_name'")
AppSetting.create(name:"'donor/manage_donor_requirements'")
AppSetting.create(name:"'donor/baby_statuses'")
AppSetting.create(name:"'donor/use_ajax_autocomplete'")
AppSetting.create(name: "'outpatient_track_race'")
AppSetting.create(name:"'donor/field_types'")
AppSetting.create(name:"'warning_level'")
AppSetting.create(name:"'receive/donor/track_depot'")
AppSetting.create(name:"'receive/donor/track_depot_default'")
AppSetting.create(name:"'receive/donor/default_receive_today'")
AppSetting.create(name:"'receive/donor/max_volume'")
AppSetting.create(name:"'receive/donor/use_autocomplete_for_donors'")
AppSetting.create(name:"'receive/donor/select_deposit_milk_type'")
AppSetting.create(name:"'receive/donor/track_expiry_time'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/select_milk_state'")
AppSetting.create(name:"'receive/donor/print_donor_label'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/donor/ensure_baby_has_been_born'")
AppSetting.create(name:"'receive/donor/ensure_donor_has_screening_results'")
AppSetting.create(name:"'receive/donor/override_milktype'")
AppSetting.create(name:"'receive/donor/override_milktype_value'")
AppSetting.create(name:"'receive/donor/set_milktype_based_on_birthday'")
AppSetting.create(name:"'receive/donor/set_milktype_based_on_birthday/use_expected_due_date'")
AppSetting.create(name:"'receive/donor/set_milktype_based_on_birthday/do_not_modify_milktype'")
AppSetting.create(name:"'receive/donor/set_milktype_based_on_nondairy_diet'")
AppSetting.create(name:"'receive/donor/allow_milktype_addition'")
AppSetting.create(name:"'receive/donor/days_for_premature_birth'")
AppSetting.create(name:"'receive/donor/term_milk_id'")
AppSetting.create(name:"'receive/donor/preterm_milk_id'")
AppSetting.create(name:"'receive/donor/lowdairy_milk_id'")
AppSetting.create(name:"'receive/donor/unknown_milk_id'")
AppSetting.create(name:"'receive/donor/excluded_milk_id'")
AppSetting.create(name:"'receive/donor/toddler_milk_id'")
AppSetting.create(name:"'receive/donor/research_milk_id'")
AppSetting.create(name:"'receive/donor/validate_type_selection_made'")
AppSetting.create(name:"'receive/donor/require_donor_to_be_approved'")
AppSetting.create(name:"'receive/donor/require_valid_lab_test_results'")
AppSetting.create(name:"'receive/donor/deposit_labels_to_print'")
AppSetting.create(name:"'receive/donor/show_baby_dob'")
AppSetting.create(name:"'receive/donor/require_valid_blood_test_results'")
AppSetting.create(name:"'receive/donor/receive_exclusion_milk_as_discarded'")
AppSetting.create(name:"'receive/donor/donor_labels_to_print'")
AppSetting.create(name:"'receive/donor/allow_expired_milk_to_be_received'")
AppSetting.create(name:"'receive/milkbank/default_milk_id'")
AppSetting.create(name:"'receive/milkbank/default_receive_today'")
AppSetting.create(name:"'receive/milkbank/max_volume'")
AppSetting.create(name:"'receive/milkbank/select_deposit_milk_type'")
AppSetting.create(name:"'receive/milkbank/track_expiry_time'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/select_milk_state'")
AppSetting.create(name:"'receive/milkbank/print_donor_label'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/validate_type_selection_made'")
AppSetting.create(name:"'receive/milkbank/deposit_labels_to_print'")
AppSetting.create(name:"'receive/milkbank/donor_labels_to_print'")
AppSetting.create(name:"'receive/milkbank/track_milkbank_donor'")
AppSetting.create(name:"'receive/milkbank/scan_milkbank_barcode'")
AppSetting.create(name:"'receive/track_container_type'")
AppSetting.create(name:"'receive/use_end_pump_date'")
AppSetting.create(name:"'receive/donor/multiple_deposits_enabled'")
AppSetting.create(name:"'receive/donor/multiple_deposits_number_of_deposits_to_receive'")
AppSetting.create(name:"'receive/donor/default_milk_type'")
AppSetting.create(name:"'donor/default_number_of_milkbank_labels'")
AppSetting.create(name:"'donor/track_calories'")
AppSetting.create(name:"'donor/calories_count_field_name'")
AppSetting.create(name:"'donor/inactivate_donors_with_lab_results_older_than'")
AppSetting.create(name:"'receive/milkbank/receive_batch'")
AppSetting.create(name:"'receive/milkbank_batch/set_milktype'")
AppSetting.create(name:"'receive/milkbank_batch/bottle_labels_addition'")
AppSetting.create(name:"'receive/milkbank_batch/default_batch_milk_bank'")
AppSetting.create(name:"'receive/milk_bank_batch/batch_require_collected_date'")
AppSetting.create(name:"'receive/milkbank_batch/track_cal_oz'")
AppSetting.create(name:"'receive/milkbank_batch/default_storage_location_id'")
AppSetting.create(name:"'receive/milkbank_batch/default_milk_id'")
AppSetting.create(name:"'receive/milkbank_batch/validate_type_selection_made'")
AppSetting.create(name:"'deposit/allow_moving_expired'")
AppSetting.create(name:"'deposit/allow_modify_deposit'")
AppSetting.create(name:"'deposit/allow_deposit_groups'")
AppSetting.create(name:"'deposit/dispose_multiple'")
AppSetting.create(name:"'pool/quantity_of_labels_to_print'")
AppSetting.create(name:"'pool/warn_if_mixing_milktypes'")
AppSetting.create(name:"'pool/show_batch_by_date_field'")
AppSetting.create(name:"'pool/soft_warn_donor_deposits_never_been_pooled'")
AppSetting.create(name:"'pool/modify_pool_volume'")
AppSetting.create(name:"'pool/track_thaw_expiry'")
AppSetting.create(name:"'pool/track_pool_volume_change_reasons'")
AppSetting.create(name:"'pool/default_pool_volume_change_reason'")
AppSetting.create(name:"'pool/custom_text_pool_volume_change_reason_id'")
AppSetting.create(name:"'nutrition/collect_deposit_nutritional_information'")
AppSetting.create(name:"'nutrition/calculate_cal_oz'")
AppSetting.create(name:"'nutrition/manually_enter_cal_oz'")
AppSetting.create(name:"'nutrition/use_gdl'")
AppSetting.create(name:"'nutrition/set_milktype'")
AppSetting.create(name:"'nutrition/set_milktype_as_cals'")
AppSetting.create(name:"'nutrition/option_to_calculate_cal_oz'")
AppSetting.create(name:"'nutrition/select_milktype_based_on_cals'")
AppSetting.create(name:"'nutrition/calculate_gdl_from_protein'")
AppSetting.create(name:"'cal_per_oz_label'")
AppSetting.create(name:"'nutrition/collect_cal_per_oz'")
AppSetting.create(name:"'nutrition/allow_viewing_expired_milk'")
AppSetting.create(name:"'nutrition/batch/override_non_dairy'")
AppSetting.create(name:"'nutrition/label_for_gdl'")
AppSetting.create(name:"'batch/automatically_dispose_of_bottle_for_testing'")
AppSetting.create(name:"'batch/automatic_disposal_reason_id'")
AppSetting.create(name:"'batch/print_extra_batch_labels'")
AppSetting.create(name:"'batch/print_label_for_testing_bottle'")
AppSetting.create(name:"'batch/allow_move_if_unapproved'")
AppSetting.create(name:"'batch/allow_modify_dispensed'")
AppSetting.create(name:"'batch/allow_modify_disposed'")
AppSetting.create(name:"'batch/collect_estimations_at_end_of_batch_process'")
AppSetting.create(name:"'batch/reactivate_disposed_bottles'")
AppSetting.create(name:"'batch/print_label_for_testing_bottle'")
AppSetting.create(name:"'batch/track_pasteurizer'")
AppSetting.create(name:"'batch/remove_information_for_op'")
AppSetting.create(name:"'batch/print_pool_labels'")
AppSetting.create(name:"'batch/number_of_pool_labels'")
AppSetting.create(name:"'batch/select_barcode_version_to_print'")
AppSetting.create(name:"'sms/license_key'")
AppSetting.create(name:"'sms/proxy_host'")
AppSetting.create(name:"'sms/proxy_port'")
AppSetting.create(name:"'sms/test_text_message'")
AppSetting.create(name:"'sms/recall'")
AppSetting.create(name:"'scan/barcode_scan_threshold_pc'")
AppSetting.create(name:"'scan/barcode_scan_threshold_pda'")
AppSetting.create(name:"'scan/barcode_scan_character_count'")
AppSetting.create(name:"milkdepot/manual_sort")
AppSetting.create(name:"'batch/batch_action_lookup'")
AppSetting.create(name:"'batch/batch_non_dispensed_action_lookup'")
AppSetting.create(name:"'dispense/print_label_without_caloric_value'")
AppSetting.create(name:"'dispense/prevent_new_label_printing_for_hospitals'")
AppSetting.create(name:"'dispense/print_single_label_for_packing'")
AppSetting.create(name:"'dispense/pack_milk'")
AppSetting.create(name:"'dispense/display_packer_name_on_packing_slip'")
AppSetting.create(name:"'dispense/auto_complete_on_dispense'")
AppSetting.create(name:"'dispense/allow_users_dispensation_to_bmt'")
AppSetting.create(name:"'dispense/internal_use_bins'")
AppSetting.create(name:"'dispense/internal_dispense_location_ids'")
AppSetting.create(name:"'dispense/internal_send_bottle_volume'")
AppSetting.create(name:"'dispense/use_pick_slips'")
AppSetting.create(name:"'dispense/manually_set_packing_user_for_initials'")
AppSetting.create(name:"'dispense/include_po_number'")
AppSetting.create(name:"'dispense/include_shipping_fee'")
AppSetting.create(name:"'dispense/allow_modify_after_dispensed'")
AppSetting.create(name:"'dispense/number_of_printed_labels'")
AppSetting.create(name:"'dispense/allow_expired_research'")
AppSetting.create(name:"'dispense/collect_invoice_to_for_packing_slip'")
AppSetting.create(name:"'dispense/allow_exclusion_milk_to_be_sent_for_research'")
AppSetting.create(name:"'dispense/check_prescription_expiry'")
AppSetting.create(name: "'dispense/use_ajax_dispensation_location_dropdown'")
AppSetting.create(name:"'dispense/collect_attn_for_packing_slip'")
AppSetting.create(name:"'dispense/allow_price_adjustments_for_packing_slip'")
AppSetting.create(name:"'dispense/track_invoice_number'")
AppSetting.create(name:"'reports/user_error_report'")
AppSetting.create(name:"'reports/batch_history'")
AppSetting.create(name:"'reports/user_error_report'")
AppSetting.create(name:"'reports/milk_finder/show_remaining_bottle_sizes'")
AppSetting.create(name:"'reports/available_dispensation/show_zero_bottle_counts'")
AppSetting.create(name:"'reports/available_dispensation/show_remaining_bottle_sizes'")
AppSetting.create(name:"'reports/dispensation/show_zero_bottle_counts'")
AppSetting.create(name:"'reports/deposit_record/show_inactive_donors'")
AppSetting.create(name:"'reports/donor_tracking_report/show_first_deposit_date'")
AppSetting.create(name:"'reports/donor_tracking_report/show_date_range'")
AppSetting.create(name:"'reports/donor_tracking_report/always_show_first_deposit_date'")
AppSetting.create(name:"'reports/milk_finder/show_milk_sources_column'")
AppSetting.create(name:"'reports/milk_finder/show_pool_not_yet_batched_field'")
AppSetting.create(name:"'reports/milk_finder/show_batch_approved_field'")
AppSetting.create(name:"'reports/deposit_record/filter_by_baby_dob'")
AppSetting.create(name:"'reports/custom_names'")
AppSetting.create(name:"'reports/custom_descriptions'")
AppSetting.create(name:"'reports/custom_subtitles'")
AppSetting.create(name:"'reports/custom_order'")
AppSetting.create(name:"'reports/volume_decimals'")
AppSetting.create(name:"'reports/enable_hmbana_report'")
AppSetting.create(name:"'reports/hmbana_starting_year'")
AppSetting.create(name:"'reports/force_volume_toggle'")
AppSetting.create(name:"'reports/milk_volume_received_by_age_group'")

AppSetting.create(name:"'reports/batch_report/show_disposed'")

AppSetting.create(name:"'permission/custom_description'")
AppSetting.create(name:"'milk_depot_label'")
AppSetting.create(name:"'geographic_region_canadian_provinces_fist'")
AppSetting.create(name:"'label/batch/show_milk_types'")
AppSetting.create(name:"'label/batch/show_protein'")
AppSetting.create(name:"'label/width'")
AppSetting.create(name:"'label/width_300_dpi'")
AppSetting.create(name:"'reports/donor_pool_report/enable_donor_name_display'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"milkdepot/manual_sort")
AppSetting.create(name:"'empi/enabled'")
AppSetting.create(name:"'empi/search_ip'")
AppSetting.create(name:"'empi/search_port'")
AppSetting.create(name:"'show_mysql_errors'")
AppSetting.create(name:"'system/salesforce/enable_salesforce'")
AppSetting.create(name:"'payment/save_credit_cards'")
AppSetting.create(name:"'system/stripe/enable_stripe'")
AppSetting.create(name:"'system/stripe/payment_range'")
AppSetting.create(name:"'system/stripe/test_mode'")
AppSetting.create(name:"'system/stripe/test_pk'")
AppSetting.create(name:"'system/stripe/test_sk'")
AppSetting.create(name:"'system/stripe/live_pk'")
AppSetting.create(name:"'system/stripe/live_sk'")
AppSetting.create(name:"'system/stripe/notification_message'")
AppSetting.create(name:"'system/stripe/contact_info'")
AppSetting.create(name:"'system/stripe/currency'")
AppSetting.create(name:"'system/salesforce/username'")
AppSetting.create(name:"'system/salesforce/password'")
AppSetting.create(name:"'system/salesforce/client_id'")
AppSetting.create(name:"'system/salesforce/client_secret'")
AppSetting.create(name:"'system/salesforce/redirect_uri'")
AppSetting.create(name:"'system/salesforce/login_uri'")
AppSetting.create(name:"'system/salesforce/security_token'")
AppSetting.create(name:"'system/quickbooks/enable_quickbooks'")
AppSetting.create(name:"'system/quickbooks/https_server_url'")
AppSetting.create(name:"'system/quickbooks/https_support_url'")
AppSetting.create(name:"'system/quickbooks/run_every_n_seconds'")
AppSetting.create(name:"'system/quickbooks/user'")
AppSetting.create(name:"'system/quickbooks/password'")
AppSetting.create(name:"'system/quickbooks/dsn'")
AppSetting.create(name:"'system/quickbooks/company_file'")
AppSetting.create(name:"'system/quickbooks/log_level'")
AppSetting.create(name:"'system/welcome_package_email_text'")
AppSetting.create(name:"'system/welcome_package_email_contact_info'")
AppSetting.create(name:"'system/final_approver_email_text'")
AppSetting.create(name:"'system/final_approver_email_subject'")
AppSetting.create(name:"'system/final_approver_email_headline'")
AppSetting.create(name:"'system/final_approver_email_contact_info'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'system/unit_of_measurement'")
AppSetting.create(name:"'system/use_only_one_uom'")
AppSetting.create(name:"'receive/donor/receive_in_ounces'")
AppSetting.create(name:"'receive/donor/convert_to_mls'")
AppSetting.create(name:"'receive/milkbank/receive_in_ounces'")
AppSetting.create(name:"'receive/milkbank/convert_to_mls'")
AppSetting.create(name:"'reports/page_size_dropdown_options'")
AppSetting.create(name:"'reports/default_page_size'")
AppSetting.create(name:"'system/uploads/endpoint'")
AppSetting.create(name:"'system/uploads/endpoint'")
AppSetting.create(name:"'db_dbname'")
AppSetting.create(name:"'db_username'")
AppSetting.create(name:"'db_password'")
AppSetting.create(name:"'db_host'")