BusTime.delete_all

BusTime.create(hour: 6,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 7,minute: 25,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 7,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 8,minute: 25,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 8,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 9,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 10,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 11,minute: 55,ampm:'am' ,board_id: 504,flag: 1)
BusTime.create(hour: 12,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 1,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 2,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 3,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 4,minute: 25,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 4,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 5,minute: 25,ampm:'pm' ,board_id: 504,flag: 1)
BusTime.create(hour: 5,minute: 55,ampm:'pm' ,board_id: 504,flag: 1)

BusTime.create(hour: 6,minute: 53,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 7,minute: 9,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 7,minute: 39,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 8,minute: 9,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 8,minute: 24,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 8,minute: 39,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 8,minute: 54,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 9,minute: 9,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 9,minute: 24,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 9,minute: 39,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 9,minute: 54,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 10,minute: 9,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 10,minute: 24,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 10,minute: 39,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 10,minute: 54,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 11,minute: 9,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 11,minute: 24,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 11,minute: 39,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 11,minute: 54,ampm:'am' ,board_id: 8,flag: 1)
BusTime.create(hour: 12,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 12,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 12,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 12,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 1,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 1,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 1,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 1,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 2,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 2,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 2,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 2,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 3,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 3,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 3,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 3,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 4,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 4,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 4,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 4,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 5,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 5,minute: 24,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 5,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 5,minute: 54,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 6,minute: 9,ampm:'pm' ,board_id: 8,flag: 1)
BusTime.create(hour: 6,minute: 39,ampm:'pm' ,board_id: 8,flag: 1)

BusTime.create(hour: 7,minute: 8,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 7,minute: 38,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 8,minute: 8,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 8,minute: 38,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 9,minute: 8,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 9,minute: 38,ampm:'pm' ,board_id: 77,flag: 1)
BusTime.create(hour: 10,minute: 8,ampm:'pm' ,board_id: 77,flag: 1)



BusTime.create(hour: 7,minute: 17,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 7,minute: 47,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 8,minute: 17,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 8,minute: 32,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 8,minute: 47,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 9,minute: 2,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 9,minute: 17,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 9,minute: 32,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 9,minute: 47,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 10,minute: 2,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 10,minute: 17,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 10,minute: 32,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 10,minute: 47,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 11,minute: 2,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 11,minute: 17,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 11,minute: 32,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 11,minute: 47,ampm:'am' ,board_id: 7,flag: 1)
BusTime.create(hour: 12,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 12,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 12,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 12,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 1,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 1,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 1,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 1,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 2,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 2,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 2,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 2,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 3,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 3,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 3,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 3,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 4,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 4,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 4,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 4,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 5,minute: 2,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 5,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 5,minute: 32,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 5,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 6,minute: 17,ampm:'pm' ,board_id: 7,flag: 1)
BusTime.create(hour: 6,minute: 47,ampm:'pm' ,board_id: 7,flag: 1)


BusTime.create(hour: 7,minute: 19,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 7,minute: 49,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 8,minute: 19,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 8,minute: 49,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 9,minute: 19,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 9,minute: 49,ampm:'pm' ,board_id: 76,flag: 1)
BusTime.create(hour: 10,minute: 19,ampm:'pm' ,board_id: 76,flag: 1)


BusTime.create(hour: 7,minute: 15,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 7,minute: 45,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 8,minute: 15,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 8,minute: 45,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 9,minute: 15,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 10,minute: 15,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 11,minute: 15,ampm:'am' ,board_id: 535,flag: 1)
BusTime.create(hour: 12,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 1,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 2,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 3,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 4,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 4,minute: 45,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 5,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 5,minute: 45,ampm:'pm' ,board_id: 535,flag: 1)
BusTime.create(hour: 6,minute: 15,ampm:'pm' ,board_id: 535,flag: 1)


BusTime.create(hour: 7,minute: 15,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 7,minute: 45,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 8,minute: 15,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 8,minute: 45,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 9,minute: 15,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 10,minute: 15,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 11,minute: 15,ampm:'am' ,board_id: 620,flag: 1)
BusTime.create(hour: 12,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 1,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 2,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 3,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 4,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 4,minute: 45,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 5,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 5,minute: 45,ampm:'pm' ,board_id: 620,flag: 1)
BusTime.create(hour: 6,minute: 15,ampm:'pm' ,board_id: 620,flag: 1)







BusTime.create(hour: 7,minute: 15,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 7,minute: 45,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 8,minute: 15,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 8,minute: 30,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 8,minute: 45,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 0,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 15,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 30,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 45,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 10,minute: 0,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 10,minute: 15,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 10,minute: 30,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 10,minute: 45,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 11,minute: 0,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 11,minute: 15,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 11,minute: 30,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 11,minute: 45,ampm:'am' ,board_id: 1,flag: 1)
BusTime.create(hour: 12,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 12,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 12,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 12,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 1,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 1,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 1,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 1,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 2,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 2,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 2,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 2,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 3,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 3,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 3,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 3,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 4,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 4,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 4,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 4,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 5,minute: 0,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 5,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 5,minute: 30,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 5,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 6,minute: 15,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 6,minute: 45,ampm:'pm' ,board_id: 1,flag: 1)


BusTime.create(hour: 7,minute: 18,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 7,minute: 48,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 8,minute: 18,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 8,minute: 48,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 18,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 9,minute: 48,ampm:'pm' ,board_id: 1,flag: 1)
BusTime.create(hour: 10,minute: 18,ampm:'pm' ,board_id: 1,flag: 1)
